#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# ~/.screenlayout/hdmi-1-0.sh
~/.config/polybar/launch.sh
flameshot &
copyq &
cbatticon &
nitrogen --restore
picom &
#repeat rate
xset r rate 300 30
#Touchpad
xinput set-prop ELAN1200:00\ 04F3:30BA\ Touchpad libinput\ Natural\ Scrolling\ Enabled 1
xinput set-prop ELAN1200:00\ 04F3:30BA\ Touchpad libinput\ Tapping\ Enabled 1

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc config border_width         2
bspc config window_gap          4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#2e3440"
bspc config active_border_color "#2e3440"
bspc config focused_border_color "#cba6f7"

bspc config focus_follows_pointer true
bspc config pointer_modifier	super

bspc rule -a copyq state=floating
